coverage:
  status:
    project:
      default:
        target: 63.5%
      important:
        paths:
          - vls-core/src/node.rs
          - vls-core/src/channel.rs
          - vls-core/src/policy/simple_validator.rs
        target: 87%
