cache:
  key: vls-global
  paths:
    - bin

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cache/cargo"

before_script:
  - ls -al
  - mkdir -p bin

stages:
  - build

rust-latest:
  tags: [ saas-linux-large-amd64 ]
  stage: build
  image: rust:latest
  cache:
    key: vls-compile-latest
    paths:
      - bin
      - .cache/cargo
  script:
    - apt-get update
    - apt-get install -y protobuf-compiler
    - rustup component add rustfmt
    - cargo test
    # ensure vls-persist builds with no-std
    - cargo build -p vls-persist --no-default-features --features no-std

rust-latest-extras:
  tags: [ saas-linux-large-amd64 ]
  stage: build
  image: rust:latest
  cache:
    key: vls-compile-latest-extras
    paths:
      - bin
      - .cache/cargo
  script:
    - apt-get update
    - apt-get install -y protobuf-compiler
    - rustup component add rustfmt
    # test LSS
    - (cd lightning-storage-server && cargo test)

rust-1.60.0:
  tags: [ saas-linux-large-amd64 ]
  stage: build
  image: rust:1.60.0
  cache:
    key: vls-compile-1_60
    paths:
      - bin
      - .cache/cargo
  script:
    - apt-get update
    - apt-get install -y protobuf-compiler
    - rustup component add rustfmt
    - cargo test

rust-1.60.0-lss:
  tags: [ saas-linux-large-amd64 ]
  stage: build
  image: rust:1.60.0
  cache:
    key: vls-compile-lss-1_60
    paths:
      - bin
      - .cache/cargo
  script:
    - apt-get update
    - apt-get install -y protobuf-compiler
    - rustup component add rustfmt
    - (cd lightning-storage-server && cargo test)

embedded:
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  image: devrandom01/rust-qemu:nightly-1-63-2022-05-16
  variables:
    RUSTFLAGS: "-C link-arg=-Tlink.x"
    CARGO_TARGET_THUMBV7M_NONE_EABI_RUNNER: "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
  script:
    - cd embedded && cargo run --release --target thumbv7m-none-eabi

demo-signer:
  tags: [ saas-linux-large-amd64 ]
  stage: build
  image: devrandom01/rust-qemu:nightly-1-63-2022-05-16
  script:
    - (cd vls-signer-stm32 && cargo build --features stm32f412 --release --bin demo_signer)
    - (cd wasm && wasm-pack test --firefox --headless && cargo test)

coverage:
  tags: [ saas-linux-large-amd64 ]
  stage: build
  image: rust:latest
  cache:
    key: vls-compile-1_60
    paths:
      - .cache/cargo
  before_script:
    - rustup component add rustfmt
    - cargo install cargo-kcov
    - apt-get update
    - apt-get install -y cmake g++ pkg-config jq
    - apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
    - cargo kcov --print-install-kcov-sh | sh
  script:
    - cd vls-core && CARGO_TARGET_DIR=target/kcov cargo kcov --verbose --lib -- --verify --exclude-pattern=/home/user/.cargo,/usr/include,/usr/src/debug,src/util/loopback.rs
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"

cargo-audit:
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo install cargo-audit
    - cargo audit
    - (cd lightning-storage-server && cargo audit)
