[workspace]

members = [
    "vls-core",
    "vls-core-test",
    "vls-server",
    "vls-frontend",

    "bolt-derive",
    "vls-persist",
    "vls-protocol",
    "vls-protocol-client",
    "vls-protocol-signer",
    "vls-proxy",
    "vlsd",
]

exclude = [
    "vls-signer-stm32",
    "embedded",
    "wasm",
    "lightning-storage-server",
]

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
