ignore:
  - "*_tests.rs"
  - "lnrod"
coverage:
  status:
    # patch coverage is flaky, so disable it
    patch:
      default:
        informational: true

    project:
      default:
        target: 60
        removed_code_behavior: adjust_base
      important:
        paths:
          - vls-core/src
        target: 80
        removed_code_behavior: adjust_base

codecov:
  notify:
    wait_for_ci: false
