ignore:
  - "*_tests.rs"
coverage:
  status:
    project:
      default:
        target: 60
        removed_code_behavior: adjust_base
      important:
        paths:
          - vls-core/src
        target: 80
        removed_code_behavior: adjust_base
