unstable_features = true
ignore = [
    "vls-core-test/tests/*.rs",
    "vls-server/src/grpc/remotesigner.rs",
    "vls-proxy/src/grpc/hsmd.rs",
]
use_small_heuristics = "Max"
match_arm_blocks = false
