[package]
name = "vls-protocol"
license = "Apache-2.0"
version = "0.11.0-rc.3"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2021"
description = "A library for implementing a Lightning signer, which externalizes and secures cryptographic operations."
homepage = "https://gitlab.com/lightning-signer/docs/"
repository = "https://gitlab.com/lightning-signer/validating-lightning-signer"

[dependencies]
serde_bolt = { version = "0.3.1", default-features = false }
bitcoin-consensus-derive = { version = "0.1.0" }
bolt-derive = { path = "../bolt-derive", version = "0.2.0" }
log = "0.4"
as-any = "0.3"
hex = { version = "0.4", default-features = false }

[dependencies.txoo]
version = "0.6.4"
#git = "https://gitlab.com/lightning-signer/txoo"
#rev = "afeb58147d6aa1a57ceee0a6128e2dca20fba157"
#branch = "main"
#path = "../../txoo"
default-features = false

[dev-dependencies]
regex = "1.5"

[features]
default = ["std"]
std = ["serde_bolt/std", "txoo/std"]
no-std = ["serde_bolt/no-std", "txoo/no-std"]

# dangerous, only for testing
log-secrets = []
