[package]
name = "vls-protocol"
license = "Apache-2.0"
version = "0.2.0-rc.1"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"
description = "A library for implementing a Lightning signer, which externalizes and secures cryptographic operations."
homepage = "https://gitlab.com/lightning-signer/docs/"
repository = "https://gitlab.com/lightning-signer/validating-lightning-signer"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = "1.0"
serde_bolt = { version = "0.2.4", default-features = false }
bolt-derive = { path = "../bolt-derive", version = "0.1.0" }
log = "0.4"
as-any = "0.3"
hex = { version = "0.4", default-features = false }

[dev-dependencies]
regex = "1.5"

[features]
std = ["serde_bolt/std"]
# dangerous, only for testing
log-secrets = []
