[package]
name = "vls-protocol"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = "1.0"
serde_bolt = { version = "0.2.4", default-features = false }
bolt-derive = { path = "../bolt-derive" }
log = "0.4"
as-any = "0.3"
hex = { version = "0.4", default-features = false }

[dev-dependencies]
regex = "1.5"

[features]
std = ["serde_bolt/std"]
# dangerous, only for testing
log-secrets = []
