[package]
name = "vls-proxy"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"
build = "build.rs"
rust-version = "1.60.0"

[features]

default = ["grpc", "main", "debug"]
grpc = ["tokio", "tokio-stream", "tonic", "prost", "async-stream", "url"]
main = ["clap", "toml", "ctrlc", "fern"]
log_pretty_print = []
debug = ["vls-core/debug", "log_pretty_print"]

[dependencies]
vls-core = { path = "../vls-core", features = ["use_backtrace"] }
vls-protocol-signer = { path = "../vls-protocol-signer" }
vls-protocol-client = { path = "../vls-protocol-client" }
vls-protocol = { path = "../vls-protocol" }
vls-frontend = { path = "../vls-frontend" }
lightning-storage-server = { path = "../lightning-storage-server", default-features = false }
nix = "0.26"
serde = "1.0"
log = "0.4"
fern = { version = "0.6", features = ["colored"], optional = true }
# .4 doesn't compile with 1.45.2
clap = { version = "3.2", optional = true, features = ["derive"] }
# match kv dep for now
toml = { version = "0.5", optional = true }
http = "0.2"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"], optional = true }
tokio-stream = { version = "0.1", optional = true }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14"
tonic = { version = "0.8", optional = true }
prost = { version = "0.11", optional = true }
# note that 3.2.4 increments nix dep in a non-semver way to 0.26
ctrlc = { version = "3.2.4", features = ["termination"], optional = true }
triggered = "0.1"
async-stream = { version = "0.3", optional = true }
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
url = { version = "2.3", optional = true }
as-any = "0.3"
hex = "0.4"
txoo-bitcoind-client = "0.1"

[dependencies.vls-server]
path = "../vls-server"
default_features = false
features = ["frontend", "persist-kv-json", "debug"]

[build-dependencies]
tonic-build = "0.8"

[lib]
name = "vls_proxy"
path = "src/lib.rs"

[[bin]]
# A single-binary drop-in replacement for hsmd with an in-process VLS
# AKA cln:inplace
name = "remote_hsmd_vls"
path = "src/vls_main.rs"

[[bin]]
# A drop-in replacement for hsmd, communicating to an embedded VLS over a serial port
# AKA cln:serial
name = "remote_hsmd_serial"
path = "src/serial_main.rs"
required-features = ["main"]

[[bin]]
# A single-binary two-process (forking) replacement for hsmd, communicating over a gRPC connection
# For integration testing only
# AKA cln:socket
name = "remote_hsmd_socket_test"
path = "src/socket_test_main.rs"
required-features = ["grpc", "main"]

[[bin]]
# A replacement for hsmd, listening to vlsd2 over a gRPC protocol
# AKA cln:socket
name = "remote_hsmd_socket"
path = "src/socket_main.rs"
required-features = ["grpc", "main"]

[[bin]]
# A signer that connects to the node using a gRPC protocol (to remote_hsmd_socket)
name = "vlsd2"
path = "src/vlsd2_main.rs"
required-features = ["grpc", "main"]

[[bin]]
name = "decode-vls"
path = "src/decode-vls.rs"
