[workspace]
resolver = "2"
members = [
  "lib",
  "lssd"
]

[workspace.dependencies]
<<<<<<< HEAD
bitcoin_hashes = ">=0.12.0,<=0.14.0"
clap = { version = "3.2" }
hex = "0.4"
log = "0.4"
prost = "0.11"
secp256k1 = { version = "0.29.0" }
thiserror = "1.0"
tokio = { version = "=1.38.1", features = ["macros"] }
# beyond 1.38 MSRV was bumped to 1.70
tonic = { version = "0.9" }
