[package]
name = "vls-protocol-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"

[features]
default = ["std"]
no-std = ["vls-core/no-std"]
std = ["vls-protocol/std", "vls-core/std"]
secp-lowmemory = ["vls-core/secp-lowmemory"]
use_backtrace = ["vls-core/use_backtrace"]
tracker_size_workaround = ["vls-core/tracker_size_workaround"]
log_pretty_print = []
debug = ["vls-core/debug", "log_pretty_print"]

[dependencies]
vls-protocol = { path = "../vls-protocol" }
log = { version = "0.4", default_features = false }
serde = { version = "1.0", default_features = false }
bit-vec = { version = "0.6", default_features = false }

[dependencies.vls-core]
path = "../vls-core"
default_features = false

[dev-dependencies.vls-core]
path = "../vls-core"
features = ["test_utils"]
